# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ShopAI Insight Chat"
client_id = "9b6bc3e7bf1edf7b2c9231a37137b1d5"
client_secret = "389c1036ea4f5b50ff607fc229cd0b0b"
application_url = "https://shopai-insight-chat.vercel.app"
tunnel_url = "https://shopai-insight-chat.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_customers,write_customers,write_products"

[auth]
redirect_urls = ["https://shopai-insight-chat.vercel.app/functions/v1/shopify_oauth_callback"]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false

[build]
dev_store_url = "https://flowtechstest.myshopify.com"
include_config_on_deploy = true
